### FUNDAMENTAL PYTHON NOTES: NUMPY
#### Created by Ugur URESIN, AI Engineer, Data Scientist

1. 1D & 2D ARRAY CREATION
2. BOOLEAN INDEXING
3. INTERSECTION, DIFFERENCE, UNION
4. RANDOM NUMBERS
5. NORMAL DISTRIBUTION
6. SORT & UNIQUE VALUES
7. ZEROS, ONES, FULL, EYE, DIAG (MATRICES)
8. NUMPY LINSPACE
9. ACCESSING & DELETING ELEMENTS
10. APPEND ELEMENTS in ARRAYS
11. ARRAY SLICING
12. SLICE IS NOT A COPY!!!
13. INSERT (NOT THE SAME WITH APPEND!)
14. STACKING (Horizontal / Vertical)
15. INDEXING
16. DIAGONALS
17. ARITHMETIC OPERATIONS

#### LIBRARY IMPORT

In [1]:
import numpy as np

#### 1D & 2D ARRAY CREATION

In [2]:
## 1D ARRAY CREATION
X = np.array([1,2,3])
print(X)

[1 2 3]


In [3]:
print(type(X)) #ndarray: n-dimensional array

<class 'numpy.ndarray'>


In [4]:
X.shape

(3,)

In [5]:
## 2D ARRAY CREATION
Y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
Y.shape

(3, 3)

In [7]:
Y.size

9

In [8]:
## MATRIX CREATION (2D-ARRAY)
np.arange(25) #25 is excluded!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### BOOLEAN INDEXING

In [10]:
X = np.arange(25).reshape(5,5)
print(X|X>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [11]:
X[(X>10) & (X<24)] = 0 #assigning 0 for the values in the given condition
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 24]]


#### INTERSECTION, DIFFERENCE, UNION

In [12]:
X = np.array([1,2,3,4,5])
Y = np.array([2,4,6,7,8])

In [13]:
np.intersect1d(X,Y)

array([2, 4])

In [14]:
np.setdiff1d(X,Y)

array([1, 3, 5])

In [15]:
np.union1d(X,Y)

array([1, 2, 3, 4, 5, 6, 7, 8])

#### RANDOM NUMBERS

In [16]:
#numpy library
#random module
#randint function 
X = np.random.randint(1, 11, size=(10,)) #create a 1d array (10,) with the random numbers between 1-10
print(X)

[ 4  1  5  2  2  6  7  3 10  1]


In [17]:
Y = np.random.randint(1, 11, size=(5,2)) #create a 2d array (5,2) with the random numbers between 1-10
print(Y)

[[8 2]
 [9 5]
 [3 4]
 [5 3]
 [1 3]]


In [18]:
np.random.randint(4,15,(3,2)) #no need to type 'size'

array([[13, 13],
       [ 6, 12],
       [ 5,  9]])

#### NORMAL DISTRIBUTION

In [19]:
np.random.normal(0, 0.1, size=(1000,1000)) #mean=0, stdev=0.1

array([[-0.00874092, -0.00759781, -0.1479328 , ..., -0.00657354,
        -0.03892668,  0.00839829],
       [-0.15622749,  0.07638552, -0.04394801, ...,  0.18385262,
         0.06250068, -0.09463125],
       [ 0.09229839,  0.0215709 ,  0.13948459, ...,  0.00675559,
         0.17735597, -0.01354161],
       ...,
       [ 0.00115577, -0.00954259, -0.01871988, ...,  0.08483752,
        -0.12601889,  0.00791221],
       [ 0.05240193,  0.00271217, -0.11022291, ...,  0.00739581,
         0.07337843, -0.16958799],
       [ 0.00699875, -0.08129575,  0.04153461, ..., -0.10787664,
        -0.00357196, -0.07126302]])

In [20]:
np.random.normal(0, 0.1, size=(1000,1000)).mean() #it has to be close to 0!

0.00015002495090711513

#### SORT & UNIQUE VALUES

In [21]:
X = np.array([3,1,5,6,3,7,8,7,1])
np.sort(X)

array([1, 1, 3, 3, 5, 6, 7, 7, 8])

In [22]:
X.sort() #this will change (sort) the original X!
print(X)

[1 1 3 3 5 6 7 7 8]


In [23]:
np.unique(X)

array([1, 3, 5, 6, 7, 8])

In [24]:
Y = np.array([[1,2,3,4], [2,3,4,5]])
np.unique(Y)

array([1, 2, 3, 4, 5])

#### ZEROS, ONES, FULL, EYE, DIAG (MATRICES)

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.full((3,2), 9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([1,3,5]) #rest are 0!

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

#### NUMPY ARANGE

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [32]:
np.arange(2,9,3)

array([2, 5, 8])

In [33]:
X = np.arange(20) #gives [0 1 2 ...19]
np.reshape(X,(2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

#### NUMPY LINSPACE

In [34]:
#np.linspace(start, stop, #numbers)
np.linspace(0, 100, 5) #100 is included!

array([  0.,  25.,  50.,  75., 100.])

In [35]:
np.linspace(0, 49) #default #numbers=50

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [36]:
np.linspace(0,2,4) #also possible to crate floats!

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [37]:
np.linspace(0,25,10, endpoint=False) #endpoint value is excluded!

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [38]:
#2D-ARRAYS with LINSPACE
np.linspace(0,20,20, endpoint=False).reshape(4,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

#### ACCESSING & DELETING ELEMENTS

**Note that:**<br>
For 1D array -> There is NO axis!<br>
For 2D array -> Row: axis=0, Column: axis=1<br>

In [39]:
## ACCCESING ELEMENTS in 1D ARRAY
X = np.array([1,2,3,4,5])
print(X[0]) #first element
print(X[1]) #second element
print(X[-1]) #last element
print(X[-2]) #second last element

1
2
5
4


In [40]:
## ACCCESING ELEMENTS in 2D ARRAY
Y = np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
Y[0,0] #first row, first column

1

In [42]:
Y[2,1] #third row, second column

8

In [43]:
## DELETING ELEMENTS in 1D ARRAY
X = np.array([1,2,3,4,5])
np.delete(X, [0,4]) #delete 1st and 5th elements, original X is NOT changed!

array([2, 3, 4])

In [44]:
X = np.delete(X, [0,4]) #original X is changed!
X

array([2, 3, 4])

In [45]:
## DELETING ELEMENTS in 2D ARRAY
Y = np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.delete(Y, 0, axis=0) #deletes the first row (original Y is NOT changed!)

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
np.delete(Y, [0,2], axis=1) #deletes the 1st and 3rd columns (original Y is NOT changed!)

array([[2],
       [5],
       [8]])

#### APPEND ELEMENTS in ARRAYS

In [48]:
## APPENDING ELEMENTS in 1D ARRAY
X = np.array([1,2,3,4,5])
X

array([1, 2, 3, 4, 5])

In [49]:
np.append(X,6)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.append(X, [6,7,8,9,0]) #the result is NOT ordered!

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [51]:
## APPENDING ELEMENTS in 2D ARRAY
Y = np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.append(Y, [[10,11,12]], axis=0) #adding a row (axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.append(Y, [[10],[11],[12]], axis=1) #adding a column (axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

#### ARRAY SLICING

**#start is included, end is excluded!**<br>
ndarry[start:end]
<br>
**#to the last element**<br>
ndarry[start:]
<br>
**#from the first element**<br> 
ndarry[:end]         

In [54]:
X = np.arange(1,25).reshape(4,6)
X

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

**To get the bold ones**<br>
[ 1,  2,  3,  4,  5,  6],<br>
[ 7,  8,  9, 10, 11, 12],<br>
[**13**, **14**, **15**, 16, 17, 18],<br>
[**19**, **20**, **21**, 22, 23, 24]]

In [55]:
X[2:4, 0:3] #2nd and 3rd rows; 1st,2nd,3rd columns

array([[13, 14, 15],
       [19, 20, 21]])

**To get the bold ones**<br>
[ 1,  2,  3,  **4**,  **5**,  **6**],<br>
[ 7,  8,  9, **10**, **11**, **12**],<br>
[13, 14, 15, **16**, **17**, **18**],<br>
[19, 20, 21, 22, 23, 24]]

In [56]:
X[0:3, 3:6]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [57]:
#2nd way
X[:3, 3:]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [58]:
# SLICE 1D/2D ARRAYS
X[:,2] #returns a 1D array

array([ 3,  9, 15, 21])

In [59]:
X[:,2:3] #returns a 2D array

array([[ 3],
       [ 9],
       [15],
       [21]])

#### SLICE IS NOT A COPY!!!

In [60]:
## EXAMPLE
X = np.arange(1,10).reshape(3,3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
Z = X[1:, 1:]
Z

array([[5, 6],
       [8, 9]])

In [62]:
Z[0,0] = 100 #assinged 100 to 1st row, 1st col element of Z
Z

array([[100,   6],
       [  8,   9]])

In [63]:
X #also x is CHANGED!!!

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [64]:
## A SLICE COPY
X = np.arange(1,10).reshape(3,3)
Z = np.copy(X[1:, 1:])
Z

array([[5, 6],
       [8, 9]])

In [65]:
#2nd way
Z = X[1:,1:].copy()
Z

array([[5, 6],
       [8, 9]])

#### INSERT (NOT THE SAME WITH APPEND!)

In [66]:
## INSERTING in 1D ARRAY
X = np.array([1,2,5,6,7])
np.insert(X, 2, [3,4])   #insert [3,4] in the 3rd (2+1) place!

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
## INSERTING in 2D ARRAY
Y = np.array([[1,2,3],[7,8,9]])
np.insert(Y, 1, [4,5,6], axis=0)   #insert [4,5,6] in the 2nd row!

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.insert(Y, 1, 100, axis=1) #add 100s in second col 

array([[  1, 100,   2,   3],
       [  7, 100,   8,   9]])

#### STACKING (Horizontal / Vertical)

In [69]:
X = np.array([1,2])
Y = np.array([[3,4], [5,6]])

In [70]:
np.vstack((X,Y)) #vertical stack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
X = X.reshape(2,1)
np.hstack((X,Y)) #horizontal stack

array([[1, 3, 4],
       [2, 5, 6]])

In [72]:
np.hstack((Y, X))

array([[3, 4, 1],
       [5, 6, 2]])

#### INDEXING

In [73]:
X = np.array([[1,2,3,4], [5,6,7,8]])
indices = np.array([2,3])
X[:,indices]

array([[3, 4],
       [7, 8]])

#### DIAGONALS

In [74]:
X = np.arange(1,13).reshape(3,4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.diag(X)

array([ 1,  6, 11])

In [76]:
np.diag(X, k=1) #1 above

array([ 2,  7, 12])

In [77]:
np.diag(X, k=-1) #1 below

array([ 5, 10])

#### ARITHMETIC OPERATIONS

1. Shapes must be identical

In [78]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

In [79]:
## ADD
np.add(X,Y)

array([ 6,  8, 10, 12])

In [80]:
## SUBTRACT
np.subtract(X,Y)

array([-4, -4, -4, -4])

In [81]:
## MULTIPLY
np.multiply(X,Y)

array([ 5, 12, 21, 32])

In [82]:
## DIVIDE
np.divide(X,Y)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

2. Structures must be broadcastable<br>
The term 'broadcastable' is used to describe how NumPy handles element-wise operations with arrays of different shapes!

In [83]:
#Example-1
X = np.array([[1,2], [3,4]])
X+3

array([[4, 5],
       [6, 7]])

In [84]:
#Example-2
Y = np.array([[0,1,2], [3,4,5], [6,7,8]])
Z = np.array([10,10,10])
Y+Z

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [85]:
#Example-3
np.full((4,4),10)*np.arange(1,5)

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [ ]:
## END OF THE CHAPTER ##